using Microsoft.UI.Xaml; using Microsoft.UI.Xaml.Controls; using Microsoft.Windows.AppNotifications; using Microsoft.Windows.AppNotifications.Builder; using NativeHub.Services;
namespace NativeHub.Pages;
public sealed partial class SettingsPage:Page
{
 private bool _loading; public SettingsPage()=>InitializeComponent();
 private async void Page_Loaded(object sender,RoutedEventArgs e){_loading=true;var s=AppServices.Settings.Current;ThemeBox.SelectedIndex=s.Theme switch{"Light"=>1,"Dark"=>2,_=>0};UnitBox.SelectedIndex=s.TemperatureUnit=="F"?1:0;TrayToggle.IsOn=s.HideToTray;BrailleNoticeToggle.IsOn=s.ShowBrailleNotice;var state=await StartupService.GetStateAsync();StartupToggle.IsOn=state==Windows.ApplicationModel.StartupTaskState.Enabled;StartupStatus.Text=state switch{Windows.ApplicationModel.StartupTaskState.DisabledByUser=>"Disabled by you in Windows Startup Apps",Windows.ApplicationModel.StartupTaskState.EnabledByPolicy=>"Enabled by organization policy",null=>"Startup integration unavailable",_=>"Keep NativeHub and its global shortcut available"};StartupToggle.IsEnabled=state is not Windows.ApplicationModel.StartupTaskState.EnabledByPolicy and not null;_loading=false;}
 private async void ThemeBox_SelectionChanged(object sender,SelectionChangedEventArgs e){if(_loading)return;AppServices.Settings.Current.Theme=(ThemeBox.SelectedItem as ComboBoxItem)?.Tag?.ToString()??"System";await AppServices.Settings.SaveAsync();(App.MainWindow as MainWindow)?.ApplyTheme();}
 private async void UnitBox_SelectionChanged(object sender,SelectionChangedEventArgs e){if(_loading)return;AppServices.Settings.Current.TemperatureUnit=(UnitBox.SelectedItem as ComboBoxItem)?.Tag?.ToString()??"C";await AppServices.Settings.SaveAsync();}
 private async void TrayToggle_Toggled(object sender,RoutedEventArgs e){if(_loading)return;AppServices.Settings.Current.HideToTray=TrayToggle.IsOn;await AppServices.Settings.SaveAsync();}
 private async void BrailleNoticeToggle_Toggled(object sender,RoutedEventArgs e){if(_loading)return;AppServices.Settings.Current.ShowBrailleNotice=BrailleNoticeToggle.IsOn;await AppServices.Settings.SaveAsync();}
 private async void StartupToggle_Toggled(object sender,RoutedEventArgs e){if(_loading)return;var state=await StartupService.SetEnabledAsync(StartupToggle.IsOn);_loading=true;StartupToggle.IsOn=state==Windows.ApplicationModel.StartupTaskState.Enabled;_loading=false;AppServices.Settings.Current.StartWithWindows=StartupToggle.IsOn;await AppServices.Settings.SaveAsync();if(state==Windows.ApplicationModel.StartupTaskState.DisabledByUser)(App.MainWindow as MainWindow)?.ShowMessage("Startup blocked","Enable NativeHub from Settings > Apps > Startup.",InfoBarSeverity.Warning);}
 private void Notification_Click(object sender,RoutedEventArgs e){if(!App.TryShowNotification("NativeHub is ready","Notifications are configured correctly."))(App.MainWindow as MainWindow)?.ShowMessage("Notification unavailable","Windows app notifications could not be registered.",InfoBarSeverity.Warning);}
 private void Exit_Click(object sender,RoutedEventArgs e)=>(App.MainWindow as MainWindow)?.Exit();
}
